version: "3.9"

services:
  api:
    build: .
    container_name: task_manager_api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      - DATABASE_URL=sqlite:///./taskmanager.db
      - SECRET_KEY=your_secret_key_here

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
